-- ============================================================================
--  Seed bank — batch 1 (v2: edgier)
--  Loads pre-written questions into public.seed_questions (status 'pending').
--  Loading is completely safe: NOTHING appears in the app until you publish.
--  Re-running this file is safe — duplicate titles are ignored.
-- ============================================================================

insert into public.seed_questions (flair, format, title, body, options, sort_order) values
  ('wyr','pollfree','Would you rather sweat maple syrup, or cry glitter?','Permanently. Both are noticeable. Only one attracts wasps.','["Maple syrup sweat","Glitter tears"]'::jsonb,0),
  ('wyr','pollfree','Would you rather have a laugh track follow you everywhere, or ominous music that swells whenever you enter a room?','Only other people can hear it. They will not mention it.','["Laugh track","Ominous swelling strings"]'::jsonb,1),
  ('wyr','pollfree','Would you rather everyone thinks you''re 15% worse looking than you are, or 15% less intelligent?','You will never be told which one is happening. You''ll just feel it.','["Worse looking","Less intelligent"]'::jsonb,2),
  ('wyr','pollfree','Would you rather be mildly haunted for the rest of your life, or thoroughly cursed for one calendar year?','Mild haunting: things move, occasionally a sigh. Thorough curse: you don''t get told the terms.','["Mildly haunted forever","Properly cursed for a year"]'::jsonb,3),
  ('wyr','pollfree','Would you rather every door you open makes a loud elevator DING, or every sneeze comes out as a three-second foghorn?','Consider libraries. Consider funerals. Consider hostage situations.','["Elevator DING on every door","Foghorn sneeze"]'::jsonb,4),
  ('wyr','pollfree','Would you rather have a packed funeral and a fairly miserable life, or a brilliant life and a funeral nobody attends?','You don''t get to attend either way, which is sort of the point.','["Packed funeral, grim life","Great life, empty funeral"]'::jsonb,5),
  ('wyr','pollfree','Would you rather always have something in your teeth that nobody ever mentions, or have everyone mention it every single time?','There is always something in your teeth. That part isn''t optional.','["Nobody ever says","Everybody always says"]'::jsonb,6),
  ('wyr','pollfree','Would you rather your search history be read aloud at your funeral, or your bank statements be read aloud at your wedding?','Full document. No skipping. Someone''s uncle has volunteered to read.','["Search history at the funeral","Bank statements at the wedding"]'::jsonb,7),
  ('wyr','pollfree','Would you rather your inner monologue be broadcast to everyone for one hour a week, or to dogs permanently?','The dogs will react. Visibly. In public.','["Humans, one hour a week","Dogs, forever"]'::jsonb,8),
  ('wyr','pollfree','Would you rather fight one horse-sized duck, or one hundred duck-sized horses?','Same fight, one winner, no weapons. The oldest argument on the internet, still unsettled.','["One horse-sized duck","One hundred duck-sized horses"]'::jsonb,9),
  ('wyr','pollfree','Would you rather only ever speak in questions, or never be able to ask one again?','Forever. Think about ordering food. Think about arguments.','["Only questions","Never a question again"]'::jsonb,10),
  ('wyr','pollfree','Would you rather smell permanently of a hospital, or permanently of a petting zoo?','You stop noticing after a week. Nobody else does.','["Hospital","Petting zoo"]'::jsonb,11),
  ('wyr','pollfree','Would you rather know exactly when you''ll die, or know exactly how — but be off by a bit on both?','The date is within five years. The cause is “broadly correct”.','["Roughly when","Roughly how"]'::jsonb,12),
  ('wyr','pollfree','Would you rather have your ex narrate your daily life, or your mother narrate your dating life?','Live commentary. Only you can hear it. Both are being honest.','["Ex narrates the day","Mum narrates the dating"]'::jsonb,13),
  ('wyr','pollfree','Would you rather be slightly famous for something deeply embarrassing, or completely anonymous forever?','Slightly famous means strangers occasionally recognise you and try not to smirk.','["Famously embarrassing","Permanently anonymous"]'::jsonb,14),
  ('tot','poll','The last slice: fight for it, or performatively refuse it?','Everyone in the room is watching and pretending not to.','["Take it","Nobly decline"]'::jsonb,15),
  ('tot','poll','Airport three hours early, or sprinting to the gate?','Be honest about which one you actually are.','["Three hours early","Full sprint"]'::jsonb,16),
  ('tot','poll','Would you rather be the funniest person in the room, or the most attractive?','You only get one and everyone can tell which you picked.','["Funniest","Most attractive"]'::jsonb,17),
  ('tot','poll','Wet bathroom floor, or a slightly damp towel?','One of these is waiting for you every single day.','["Wet floor","Damp towel"]'::jsonb,18),
  ('tot','poll','Loud chewer, or a leg-jiggler?','You have to sit next to them for the next six hours.','["Loud chewer","Leg-jiggler"]'::jsonb,19),
  ('tot','poll','Reply-all catastrophe, or drunk text to the wrong person?','One is career damage, one is personal. Pick your ruin.','["Reply-all","Drunk text"]'::jsonb,20),
  ('tot','poll','Cold pizza for breakfast, or reheated pizza that has gone slightly rubbery?','There is a correct answer and one of you is wrong.','["Cold, straight from the fridge","Reheated and rubbery"]'::jsonb,21),
  ('tot','poll','Being read the wrong name at your own award ceremony, or having your microphone cut mid-speech?','The room is full. It''s being filmed.','["Wrong name","Mic cut"]'::jsonb,22),
  ('hot','pollfree','Cereal is just cold soup and we should treat it with that respect.','Bowl. Spoon. Liquid base. Solid garnish. It''s soup. You have no rebuttal.','["It''s soup","It''s absolutely not soup"]'::jsonb,23),
  ('hot','pollfree','Weddings are a colossal waste of money and almost everyone privately agrees.','The photos are nice. That''s about £20,000 a photo.','["Agree","Disagree"]'::jsonb,24),
  ('hot','pollfree','Most people''s dogs are badly behaved and the owners are in total denial.','“He''s friendly!” is not a behavioural qualification.','["Agree","Disagree"]'::jsonb,25),
  ('hot','pollfree','Funerals should be significantly more fun than they currently are.','The guest of honour would probably agree.','["Agree","Disagree"]'::jsonb,26),
  ('hot','pollfree','Nobody genuinely enjoys camping. They enjoy having gone camping.','Two entirely different experiences, one of which involves a tent.','["Agree","Disagree"]'::jsonb,27),
  ('hot','pollfree','Read receipts were a catastrophic mistake for human civilisation.','We were not built to know. We are not coping.','["Agree","Disagree"]'::jsonb,28),
  ('hot','pollfree','Birthday cake in an office is a form of workplace coercion.','Nobody wants it. Everybody sings. The cake is always slightly dry.','["Agree","Disagree"]'::jsonb,29),
  ('hot','pollfree','Pineapple on pizza is completely fine. Bad cheese is the actual crime.','You''ve spent a decade shouting at the wrong topping.','["Agree — cheese is the crime","Disagree — pineapple is the crime"]'::jsonb,30),
  ('hypo','pollfree','You can teleport anywhere instantly, but you always arrive completely naked.','No warning to anyone at the destination. Still worth it?','["Absolutely worth it","Absolutely not"]'::jsonb,31),
  ('hypo','pollfree','You''re offered immortality, but you keep ageing normally.','You will not die. You will simply continue.','["Take it","Decline"]'::jsonb,32),
  ('hypo','free','You get a pet dragon. It is the size of a hamster, it is permanently furious, and it hates you specifically.','It cannot be rehomed. What do you do with your tiny nemesis?','[]'::jsonb,33),
  ('hypo','pollfree','A wizard offers you ten extra years of life. You must spend all ten inside a motorway service station.','Fully catered. Free WiFi. You may not leave.','["Take the ten years","Politely decline"]'::jsonb,34),
  ('hypo','pollfree','Everyone on earth gets £1,000, but everyone also finds out it was your doing and is mildly annoyed about it.','Not grateful. Not furious. Just a bit irritated, forever.','["Press it","Leave it"]'::jsonb,35),
  ('hypo','free','Your pet can talk for exactly one hour — and they''ve chosen the hour. It''s 3am.','They have clearly been saving things up. What''s the first thing they say?','[]'::jsonb,36),
  ('hypo','pollfree','You can rewind ten seconds, once per day, but everyone nearby feels a brief unexplained sadness.','They won''t know why. You will.','["Use it daily","Never use it"]'::jsonb,37),
  ('hypo','free','You wake up fluent in a language nobody can identify.','It is definitely a real language. It is definitely being spoken somewhere. Where do you start?','[]'::jsonb,38),
  ('moral','pollfree','You find a wallet with £500 cash and an address inside. Nobody saw you pick it up.','Be honest with yourself before you answer. Most people lie about this one.','["Return every penny","Keep it"]'::jsonb,39),
  ('moral','pollfree','You''re giving the wedding speech and you are genuinely certain the marriage will not last.','You have the microphone. Two hundred people are smiling at you.','["Give the warm speech anyway","Find a way to be honest"]'::jsonb,40),
  ('moral','pollfree','Your friend asks if you like the very expensive gift they clearly saved up for. You don''t.','They''re watching your face right now.','["Tell the truth","Lie beautifully"]'::jsonb,41),
  ('moral','pollfree','You watch a struggling colleague steal something small from work.','You know their situation. You also know the shop floor has cameras.','["Say nothing","Report it"]'::jsonb,42),
  ('moral','pollfree','You could anonymously tell a stranger their partner is cheating — but you''d be wrong about 20% of the time.','You will never find out which one this was.','["Send it","Don''t send it"]'::jsonb,43),
  ('moral','pollfree','Your best friend asks you to be their alibi. They won''t say what for.','They''ve never asked you for anything before.','["Do it","Refuse"]'::jsonb,44),
  ('moral','pollfree','You find your partner''s diary lying open on the exact page with your name underlined.','You have roughly eleven seconds before they come back.','["Read it","Walk away"]'::jsonb,45),
  ('moral','pollfree','A stranger''s card is declined in front of a long queue and you can afford to cover it.','They have not asked. They are going quite red.','["Step in","Stay out of it"]'::jsonb,46),
  ('unpop','pollfree','Children should not be invited to weddings and everyone secretly knows it.','Someone''s about to reply furiously and prove the point.','["Agree","Disagree"]'::jsonb,47),
  ('unpop','pollfree','Birthdays should quietly stop being an event after roughly thirty.','A message and a nice dinner. That is the entire ceremony.','["Agree","Disagree"]'::jsonb,48),
  ('unpop','pollfree','Group holidays are almost never worth it and are mostly an act of endurance.','Someone wants a museum. Someone wants a nap. Nobody says anything for four days.','["Agree","Disagree"]'::jsonb,49),
  ('unpop','pollfree','Almost nobody actually enjoys champagne. They enjoy the occasion and have confused the two.','It''s fizzy and slightly sour and we''ve all agreed to pretend.','["Agree","Disagree"]'::jsonb,50),
  ('unpop','pollfree','Most books would have been better as a long article.','Three good chapters and two hundred pages of stretching.','["Agree","Disagree"]'::jsonb,51),
  ('unpop','pollfree','Surprise parties are almost entirely for the person throwing them.','Watch who''s filming and you''ll know who it''s for.','["Agree","Disagree"]'::jsonb,52),
  ('island','free','Stranded forever. One smell — just the smell, no source, no food attached.','Rain on hot tarmac. A specific person''s kitchen. Petrol, if you''re honest. What''s yours?','[]'::jsonb,53),
  ('island','pollfree','One companion on the island: someone deeply competent, or someone genuinely funny?','It may be a very long time. Both of you will change.','["Competent","Funny"]'::jsonb,54),
  ('island','free','One condiment. Forever. Choose extremely carefully.','There is no food to put it on yet. That''s a separate problem.','[]'::jsonb,55),
  ('island','free','You may bring one utterly useless luxury item — nothing practical, nothing that could help you escape.','Pure comfort or pure vanity only. What are you taking?','[]'::jsonb,56),
  ('island','pollfree','Would you rather be stranded alone, or with one person who never stops talking?','They are pleasant. They are relentless. They mean well.','["Alone","The talker"]'::jsonb,57),
  ('shower','free','You will never know what your own voice sounds like to everyone else.','Everyone you''ve ever met knows something about you that you can''t access.','[]'::jsonb,58),
  ('shower','free','Every photo of you is a photo of light that bounced off you and immediately left.','You are not in the picture. You never were.','[]'::jsonb,59),
  ('shower','free','At some point your parents put you down and never picked you up again — and nobody noticed the last time.','It just quietly stopped happening one afternoon.','[]'::jsonb,60),
  ('shower','free','Somewhere right now, someone is having the best day of their entire life.','And someone is having their worst. Simultaneously. Constantly. Forever.','[]'::jsonb,61),
  ('shower','free','There is a version of you that only exists in other people''s heads, and you''ll never get to meet him.','Several versions, actually. None of them accurate. All of them convincing.','[]'::jsonb,62),
  ('shower','free','You''ve almost certainly already met most of the people you''ll ever know.','The cast list is mostly closed. The auditions are basically over.','[]'::jsonb,63),
  ('free','free','What''s the pettiest hill you would genuinely die on?','No stakes. No importance. Absolute conviction.','[]'::jsonb,64),
  ('free','free','What''s a lie you tell regularly that harms precisely nobody?','We all have one. Some of us have a system.','[]'::jsonb,65),
  ('free','free','What''s something you loudly pretend to enjoy?','You''ve been doing it for years. It''s gone too far to stop now.','[]'::jsonb,66),
  ('free','free','What''s the most unhinged thing in your camera roll right now?','Nothing incriminating. Just genuinely unexplainable.','[]'::jsonb,67),
  ('free','free','What''s a food combination you enjoy that would get you thrown out of a restaurant?','Defend it. Fully. With confidence.','[]'::jsonb,68)
on conflict do nothing;

-- How many are now waiting:
select status, count(*) as questions from public.seed_questions group by status;
